services:
  postgres:
    image: postgres:16
    container_name: tc3-postgres
    environment:
      POSTGRES_DB: scheduling
      POSTGRES_USER: scheduling_user
      POSTGRES_PASSWORD: scheduling_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: