spring.application.name=history-service
server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/history}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:adminPostgres}
spring.jpa.hibernate.ddl-auto=update

spring.graphql.graphiql.enabled=true

# JWT CONFIG
app.security.jwt.secret=${AUTH_JWT_SECRET:tc3-local-development-secret-key-2026}
