spring.application.name=scheduling-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/scheduling
spring.datasource.username=scheduling_user
spring.datasource.password=scheduling_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true